- name: Ensure the target working directory is empty
  block:
    - name: Remove current working directory
      file:
        path: "{{ working_dir }}"
        state: absent
    - name: Create working directory
      file:
        path: "{{ working_dir }}"
        state: directory
- name: Download StumpWM Repository
  git:
    repo: "{{ repository }}"
    dest: "{{ working_dir }}"
    version: 'HEAD'
  notify:
    - Set permission on StumpWM working directory
    - Build StumpWM
    - Install StumpWM
- name: Install StumpWM Contributions
  git:
    repo: "{{ repository_contrib }}"
    dest: "{{ working_dir_contrib }}"
    version: 'HEAD'
